### PR TITLE
bug(#4135): add XMIR error if object name mismatched

### LINKED ISSUE #4135: Inconsistent XMIR Behavior: Unintended Exception Instead of `<error/>` Generation
After #4130 is resolved, let's think why do we treat this problem differently than all others? Why do we throw an exception instead of adding an `<error/>` to XMIR? It seems to be more appropriate to use XMIR `<errors/>` element.

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've updated `MjParse.parsed()` to add error information under the `errors` XMIR node, instead of throwing `IllegalArgumentException`.

closes #4135
History:
- **bug(#4135): errors are there**
- **bug(#4135): passes with correct tests**
- **bug(#4135): inline**
- **bug(#4135): comments off**

### CODE REVIEW

**Comment by h1alexbel** [comment]
https://github.com/objectionary/eo/issues/4178

**Comment by h1alexbel** [comment]
blocked by https://github.com/objectionary/eo/issues/4181

**Comment by h1alexbel** [comment]
@maxonfjvipon please check

File: eo-maven-plugin/src/main/java/org/eolang/maven/MjParse.java [hunk 1]
```diff
@@ -146,12 +149,26 @@ private Node parsed(final Path source, final String identifier) throws IOExcepti
...
+                        .add("error")
+                        .attr("check", "validate-object-name")
+                        .attr("severity", "critical")
+                        .set(
+                            String.format(
+                                "Tojo identifier '%s' does not match to result object name '%s'",
+                                identifier, name
+                            )
+                        )
+                ).apply(xmir.inner());
```
Comment (maxonfjvipon) [inline eo-maven-plugin/src/main/java/org/eolang/maven/MjParse.java:166]: @h1alexbel let's move `xmir.inner()` to a separated variable and use it here and in `return` statement

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

**Comment by h1alexbel** [comment]
@maxonfjvipon updated. Take a look, please

**Review by maxonfjvipon — APPROVED** [review]

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

File: eo-maven-plugin/src/main/java/org/eolang/maven/MjParse.java [hunk 2]
```diff
@@ -145,15 +148,30 @@ private Node parsed(final Path source, final String identifier) throws IOExcepti
...
+                        .add("error")
+                        .attr("check", "validate-object-name")
+                        .attr("severity", "critical")
+                        .set(
+                            String.format(
+                                "Tojo identifier '%s' does not match to result object name '%s'",
+                                identifier, name
+                            )
+                        )
+                ).apply(document);
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/MjParse.java:167]: @h1alexbel you can use `applyQuietly()` with the same result, but less lines of code

**Review by yegor256 — CHANGES_REQUESTED** [review]

**Comment by h1alexbel** [comment]
@yegor256 updated. Take a look, please

**Review by yegor256 — APPROVED** [review]

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the review! Your effort earned you +4 points: +12 base, -24 for self-review, +2 for 200 hits-of-code (capped at 16), -10 for few comments, +2.5 for 10 comments (capped at 8), adjusted to minimum 4 points. Your balance is now [+46](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and aim for more comments next time! 💻👍

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Great job on the review, but we've got some room for improvement. You snagged 4 points this time: 12 for showing up, but we had to dock 10 because there were only 2 comments. We bumped you up 2 points to keep things fair. Remember, more comments can boost your score – up to 8 points for chatty reviews! Your current balance is [-770](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep at it, and let's aim for more detailed feedback next time to max out those bonus points! 💪

**Comment by 0crat** [comment]
@h1alexbel Thank you for your contribution! We've reviewed your work and awarded you +16 points, in line with our [policy](https://www.yegor256.com/2014/11/14/hits-of-code.html) for code contributions. Your commitment to quality is appreciated. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the great work! Your current balance stands at [+496](https://www.eolang.org/zerocracy/objectionary-vitals.html). We look forward to your continued contributions to the project.
