### PR TITLE
#1563 clear error message for wrong attrs

### LINKED ISSUE #1563: Can't dataize eo program with `cage`: `IndexOutOfBoundsException`
I'm trying to dataize the next `eo` program:
```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[val] > container
  val > @

[] > loop
  cage 0 > index
  seq > @
    index.write container 1
    stdout
      sprintf
        "%s"
        index
    index.write container 2
    stdout
      sprintf
        "%s"
        index
    index.write container 3
    stdout
      sprintf
        "%s"
        index
    TRUE
```
Expected behaviour: program compiles and dataizes successfully.
Actual behaviour: I get the next exception:
```sh
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.eolang.PhDefault.attr(PhDefault.java:231)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:83)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhImmovable.attr(PhImmovable.java:80)
	at org.eolang.PhLocated.attr(PhLocated.java:94)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.Dataized.take(Dataized.java:87)
	at EOorg.EOeolang.EOseq.lambda$new$0(EOseq.java:63)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:255)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:256)
	at org.eolang.Dataized.take(Dataized.java:87)
	at org.eolang.Dataized.take(Dataized.java:127)
	at org.eolang.Main.run(Main.java:190)
	at org.eolang.Main.main(Main.java:98)
```

### PR DESCRIPTION
**Pull request by mximp**
closes #1563

Error message would be:
```
EOorg.EOeolang.EOerror$ExError: EOorg.EOeolang.EOstringν69="EOorg.EOeolang.EOcage.Writeν64 has just 1 attribute(s), can't read the 1-th one"SF
```

### CODE REVIEW

**Comment by mximp** [comment]
@volodya-lombrozo please check

File: eo-runtime/src/main/java/org/eolang/PhDefault.java [hunk 1]
```diff
@@ -210,22 +210,25 @@ public final Attr attr(final int pos) {
                 )
             );
         }
-        int idx;
-        for (idx = 0; idx < pos; ++idx) {
+        Attr attr = this.attr(this.order.get(0));
```
Comment (volodya-lombrozo) [inline eo-runtime/src/main/java/org/eolang/PhDefault.java:213]: @mximp Is it good way to assign "first" attribute here? What if  attribute with id `this.order.get(0)` doesn't exist?

File: eo-runtime/src/main/java/org/eolang/PhDefault.java [hunk 2]
```diff
@@ -210,22 +210,25 @@ public final Attr attr(final int pos) {
...
-                        this.order.size(), pos
+                        "%s has just %d attribute(s), can't read the %d-th one",
+                        this,
+                        this.order.size(),
+                        pos
                     )
                 );
             }
             final String name = this.order.get(idx);
+            attr = this.attr(this.order.get(idx));
```
Comment (volodya-lombrozo) [inline eo-runtime/src/main/java/org/eolang/PhDefault.java:226]: @mximp We call it on every loop iteration. Apparently it's time consuming. What do you think?

File: eo-runtime/src/main/java/org/eolang/PhDefault.java [hunk 3]
```diff
@@ -210,22 +210,25 @@ public final Attr attr(final int pos) {
                 )
             );
         }
-        int idx;
-        for (idx = 0; idx < pos; ++idx) {
+        Attr attr = this.attr(this.order.get(0));
+        for (int idx = 0; idx <= pos; ++idx) {
```
Comment (volodya-lombrozo) [inline eo-runtime/src/main/java/org/eolang/PhDefault.java:214]: @mximp Why do you need equality here? Do you have any proofs (tests)?

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]

File: eo-runtime/src/main/java/org/eolang/PhDefault.java (hunk 1 above)
Comment (mximp) [reply eo-runtime/src/main/java/org/eolang/PhDefault.java:213]: @volodya-lombrozo it always exists if all previous validations are passed.

File: eo-runtime/src/main/java/org/eolang/PhDefault.java (hunk 2 above)
Comment (mximp) [reply eo-runtime/src/main/java/org/eolang/PhDefault.java:226]: @volodya-lombrozo We have to get the attribute on each iteration to check wether it's vararg or not. Vararg makes the iteration to stop.

File: eo-runtime/src/main/java/org/eolang/PhDefault.java (hunk 3 above)
Comment (mximp) [reply eo-runtime/src/main/java/org/eolang/PhDefault.java:214]: @volodya-lombrozo `idx` iterates through all arg positions up until `pos` inclusive. Previously the iteration was done through all but the `pos` itself and `pos` was queried outside the loop. I've changed it to avoid duplication.

Comment (mximp) [reply eo-runtime/src/main/java/org/eolang/PhDefault.java:214]: @volodya-lombrozo new functional changes are introduced here. This code is covered by existing tests.

**Comment by mximp** [comment]
@volodya-lombrozo please check my comments

**Review by volodya-lombrozo — APPROVED** [review]
@mximp Looks good to me

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge
