### PR TITLE
#1441 eo-runtime dependency test fix

### LINKED ISSUE #1441: The problem with tests during releasing a new plugin version
We have faced with the problem during releasing new `0.28.11` version of the plugin. It's important to implement a stable solution in order to prevent the same errors in the future.
[The problem](https://github.com/objectionary/eo/issues/1437).
[Fast fix](https://github.com/objectionary/eo/pull/1438).

### PR DESCRIPTION
**Pull request by mximp**
#1441 Added new matcher that validates folder content

### CODE REVIEW

**Comment by mximp** [comment]
@volodya-lombrozo please check

File: eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+ * Asserting that path contains a file matching provided glob.
+ * @since 0.28.12
+ * @checkstyle ProtectedMethodInFinalClassCheck (30 lines)
+ */
+final class ContainsFile extends TypeSafeMatcher<Path> {
+
+    /**
+     * Glob pattern to match against.
+     */
+    private final String glob;
```
Comment (volodya-lombrozo) [inline eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java:48]: @mximp maybe the "pattern" name fits better here. What do you think?

File: eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+        this.glob = glob;
+    }
+
+    @Override
+    public void describeTo(final Description description) {
+        description.appendText(String.format("Matching glob=`%s`", this.glob));
+    }
+
+    @Override
+    protected boolean matchesSafely(final Path item) {
```
Comment (volodya-lombrozo) [inline eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java:64]: @mximp I believe it could be written shorter , for example:
```java
final PathMatcher matcher = FileSystems.getDefault().getPathMatcher(String.format("glob:%s", this.glob));
return Files.walk(item).anyMatch(matcher::matches);
```
In that case you don't need `ActionOnMatch` class

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]

File: eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java (hunk 1 above)
Comment (mximp) [reply eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java:48]: @volodya-lombrozo `pattern` can mean regex or anything else. `glob` in this case reflects expected pattern type.

**Comment by mximp** [comment]
@volodya-lombrozo fixed. please check.

File: eo-maven-plugin/src/test/java/org/eolang/maven/ResolveMojoTest.java [hunk 3]
```diff
@@ -85,11 +85,11 @@ void resolveWithoutAnyDependencies(@TempDir final Path temp) throws IOException
...
         final Path target = temp.resolve("target");
         this.resolve(new DummyCentral(), foreign, target);
-        final Path path = temp.resolve("target/06-resolve/org.eolang/eo-runtime/-/0.28.11");
+        final Path path = temp.resolve("target/06-resolve/org.eolang/eo-runtime/-/");
         MatcherAssert.assertThat(path.toFile(), FileMatchers.anExistingDirectory());
         MatcherAssert.assertThat(
-            path.resolve("eo-runtime-0.28.11.jar").toFile(),
-            FileMatchers.anExistingFile()
+            path,
+            new ContainsFile("**/*.jar")
```
Comment (volodya-lombrozo) [inline eo-maven-plugin/src/test/java/org/eolang/maven/ResolveMojoTest.java:92]: @mximp I believe it would be better to use more precise pattern, like `**/eo-runtime-*.jar`, because the test can give us false-positive, if we add some other dependency.

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]

File: eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+                            String.format(
+                                "glob:%s",
+                                this.glob
+                            )
+                        )::matches
+                );
+        } catch (final IOException ex) {
+            throw new IllegalStateException(
+                String.format(
+                    "Error while matching glob=`%s` for %s",
```
[the remark this answers is not in the document]
Comment (mximp) [reply eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java:74]: @volodya-lombrozo glob value is enclosed as it's literal. For second parameter it's just path. Why would we want to enclose it?

File: eo-maven-plugin/src/test/java/org/eolang/maven/ResolveMojoTest.java (hunk 3 above)
Comment (mximp) [reply eo-maven-plugin/src/test/java/org/eolang/maven/ResolveMojoTest.java]: @volodya-lombrozo corrected

**Comment by mximp** [comment]
@volodya-lombrozo please re-check

File: eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+import java.nio.file.FileSystems;
+import java.nio.file.Files;
+import java.nio.file.Path;
+import org.hamcrest.Description;
+import org.hamcrest.TypeSafeMatcher;
+
+/**
+ * Asserting that path contains a file matching provided glob.
+ * @since 0.28.12
+ * @checkstyle ProtectedMethodInFinalClassCheck (30 lines)
```
Comment (volodya-lombrozo) [inline eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java:36]: @mximp you can declare `matchesSafely` as `public` and remove `ProtectedMethodInFinalClassCheck`. We did the same in all other cases related to `TypeSafeMatcher`.

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]

File: eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java (hunk 5 above)
Comment (mximp) [reply eo-maven-plugin/src/test/java/org/eolang/maven/ContainsFile.java:36]: @volodya-lombrozo didn't know that. Thanks!

**Comment by mximp** [comment]
@volodya-lombrozo done

**Review by volodya-lombrozo — APPROVED** [review]
Looks good to me

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge
