### PR TITLE
2442 error handling

### LINKED ISSUE #2442: rust inserts' error handling
Now it does not provide any information if something goes wrong in rust insert.
It is necessary to implement error handling for rust insert. For example return `EOError` and save stacktrace somewhere in `Univese`

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2442

---

## PR-Codex overview
This PR focuses on improving error handling in the code. It includes the following notable changes:

- Changed the `ExFailure` class to be non-final.
- Added the `EOError` variant to the `EO` enum in the Rust code.
- Added the `ExNative` class to handle exceptions in native methods.
- Updated the `EOrust` class to handle error messages from native functions.
- Added the `UniverseSafe` class to store exceptions thrown in native functions.

> The following files were skipped due to too many changes: `eo-runtime/src/main/java/org/eolang/UniverseSafe.java`, `eo-runtime/src/main/java/org/eolang/Universe.java`, `eo-runtime/src/main/java/org/eolang/UniverseDefault.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please review

File: eo-runtime/src/main/java/org/eolang/ExNative.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+ */
+
+package org.eolang;
+
+/**
+ * Exception in native method.
+ *
+ * @since 0.32
+ */
+public final class ExNative extends ExFailure {
```
Comment (Graur) [inline eo-runtime/src/main/java/org/eolang/ExNative.java:32]: @levBagryansky Why did you extend `ExFailure` class instead of extend `ExAbstract` class?

File: eo-runtime/src/test/eo/org/eolang/rust-tests.eo [hunk 2]
```diff
@@ -254,3 +254,25 @@
...
+    *
+      []
+  assert-that > @
+    try
+      []
+        err > @
+      [e]
+        e > @
+      nop
+    $.string-starts-with "Rust insert "
```
Comment (Graur) [inline eo-runtime/src/test/eo/org/eolang/rust-tests.eo:278]: @levBagryansky I expect "Error happened" string here. maybe we can use `contains-string` instead of  `string-starts-with`?

**Review by Graur — CHANGES_REQUESTED** [review]
@levBagryansky Good one, just a few comments from my side:

File: eo-runtime/src/main/java/org/eolang/ExNative.java (hunk 1 above)
Comment (levBagryansky) [reply eo-runtime/src/main/java/org/eolang/ExNative.java:32]: @Graur According to `EOError.java`:
```
 * <p>You are NOT supposed to use this object programmatically. It is only
 * used from EO, but not from Java. From Java you just throw
 * {@link ExFailure}. It will be properly caught and converted to the error.
 * Again, DON'T USE THIS OBJECT PROGRAMMATICALLY.
 *
```
So I make it in order to manage this failure on `eo` side

Comment (Graur) [reply eo-runtime/src/main/java/org/eolang/ExNative.java:32]: @levBagryansky  So if you extend your own error from `ExAbstract` class we will not see the error message at all?

Comment (levBagryansky) [reply eo-runtime/src/main/java/org/eolang/ExNative.java:32]: @Graur yes, the test will be failed with ExNative exception

**Comment by levBagryansky** [comment]
@Graur please check

**Review by Graur — APPROVED** [review]
@levBagryansky Good one!
@yegor256 Could you please take a look?

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge
