### PR TITLE
sprintf with byte array

### LINKED ISSUE #1049: `sprintf` with `%c`
code
```java
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

+package sandbox

[args...] > app
  stdout (sprintf "%c" (56.as-bytes.slice 7 1)) > @
```

current result:
```
Exception in thread "main" java.util.IllegalFormatConversionException: c != [B
        at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
        at java.util.Formatter$FormatSpecifier.printCharacter(Unknown Source)
        at java.util.Formatter$FormatSpecifier.print(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.lang.String.format(Unknown Source)
        at EOorg.EOeolang.EOtxt.EOsprintf.lambda$new$0(EOsprintf.java:71)
        at org.eolang.AtComposite.get(AtComposite.java:73)
        at org.eolang.CachedPhi.get(CachedPhi.java:81)
        at org.eolang.PhDefault.attr(PhDefault.java:241)
        at org.eolang.PhLocated.attr(PhLocated.java:99)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhNamed.attr(PhNamed.java:92)
        at org.eolang.PhSafe.attr(PhSafe.java:94)
        at org.eolang.Dataized.take(Dataized.java:81)
        at org.eolang.Param.weak(Param.java:101)
        at org.eolang.Param.strong(Param.java:80)
        at EOorg.EOeolang.EOio.EOstdout.lambda$new$0(EOstdout.java:66)
        at org.eolang.AtComposite.get(AtComposite.java:73)
        at org.eolang.CachedPhi.get(CachedPhi.java:81)
        at org.eolang.PhDefault.attr(PhDefault.java:241)
        at org.eolang.PhLocated.attr(PhLocated.java:99)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhDefault.attr(PhDefault.java:242)
        at org.eolang.Dataized.take(Dataized.java:81)
        at org.eolang.Dataized.take(Dataized.java:121)
        at org.eolang.Main.run(Main.java:184)
        at org.eolang.Main.main(Main.java:92)
```

### PR DESCRIPTION
**Pull request by Graur**
Closes #1049

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@EugeneDar please, review

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java [hunk 1]
```diff
@@ -65,13 +70,63 @@ public EOsprintf(final Phi sigma) {
                     final String format = new Param(rho, "format").strong(String.class);
                     final Phi[] args = new Param(rho, "args").strong(Phi[].class);
                     final Collection<Object> items = new LinkedList<>();
-                    for (final Phi arg : args) {
-                        items.add(new Dataized(arg).take());
+                    for (int idx = 0; idx < args.length; idx += 1) {
+                        items.add(format(args[idx], idx, format));
                     }
                     return new Data.ToPhi(String.format(Locale.US, format, items.toArray()));
```
Comment (EugeneDar) [inline eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:76]: @Graur Maybe we don't need `Locale.US` here

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java [hunk 2]
```diff
@@ -65,13 +70,63 @@ public EOsprintf(final Phi sigma) {
                     final String format = new Param(rho, "format").strong(String.class);
                     final Phi[] args = new Param(rho, "args").strong(Phi[].class);
                     final Collection<Object> items = new LinkedList<>();
-                    for (final Phi arg : args) {
-                        items.add(new Dataized(arg).take());
+                    for (int idx = 0; idx < args.length; idx += 1) {
```
Comment (EugeneDar) [inline eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:73]: @Graur I think you can use `++idx` here

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java [hunk 3]
```diff
@@ -65,13 +70,63 @@ public EOsprintf(final Phi sigma) {
...
+     *
+     * @param format Format string
+     * @param index Index of the argument in array
+     * @return Index of th flag
+     */
+    private static int findOccurrence(final String format, final int index) {
+        final String flag = "%";
+        String fmt = format;
+        int result = -1;
+        for (int occurrence = 0; occurrence <= index; occurrence += 1) {
```
Comment (EugeneDar) [inline eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:118]: @Graur I think you can use `++occurrence` here

File: eo-runtime/src/test/eo/org/eolang/txt/sprintf-tests.eo [hunk 4]
```diff
@@ -43,3 +43,8 @@
       "Jeff"
       "X"
     $.equal-to "Привет 3.14 Jeff X!"
+
+[] > prints-bytes-string
+  assert-that > @
+    sprintf "%c" (56.as-bytes.slice 7 1)
```
Comment (EugeneDar) [inline eo-runtime/src/test/eo/org/eolang/txt/sprintf-tests.eo:49]: @Graur are we have difference between `%s` and `%c` in EO. Since we don't have a Char type, it probably makes sense to use the `%s` here.

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java [hunk 5]
```diff
@@ -65,13 +70,63 @@ public EOsprintf(final Phi sigma) {
...
+     *  only character formatting. It means that byte array
+     *  become an first bytes character string. We need to
+     *  support another flags, like %a, %o, %s, etc.
+     */
+    private static Object format(final Phi phi, final int index, final String format) {
+        final Object arg = new Dataized(phi).take();
+        Object result = arg;
+        if (arg instanceof byte[]) {
+            final int occurrence = findOccurrence(format, index);
+            final String flag = format.substring(occurrence, occurrence + 2);
```
Comment (EugeneDar) [inline eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:99]: @Graur If I understand correctly, the `findOccurrence` function can return `-1`. Then when we take a substring we will get an error, shouldn't we catch or check it here?

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java (hunk 1 above)
Comment (Graur) [reply eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:76]: @EugeneDar I didn't modified this code

File: eo-runtime/src/test/eo/org/eolang/txt/sprintf-tests.eo (hunk 4 above)
Comment (Graur) [reply eo-runtime/src/test/eo/org/eolang/txt/sprintf-tests.eo:49]: @EugeneDar please, read the related issue: #1049

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java (hunk 2 above)
Comment (Graur) [reply eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:73]: @EugeneDar if I do so, I get checkstyle's [IllegalTokenCheck](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.html)

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java (hunk 3 above)
Comment (Graur) [reply eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:118]: @EugeneDar if I do so, I get checkstyle's error [IllegalTokenCheck](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.html):  Using '++' is not allowed.

File: eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java (hunk 5 above)
Comment (Graur) [reply eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java:99]: @EugeneDar Indeed, if we have no `%` sign in formatted string we get an error. I will fix it and add new test, thanks!

**Comment by Graur** [comment]
@EugeneDar please, check again

**Review by EugeneDar — APPROVED** [review]
@Graur good one

**Comment by yegor256** [comment]
@rultor merge
