### PR TITLE
better logging of errors

### LINKED ISSUE #3747: error logging doesn't show full stacktrace

### PR DESCRIPTION
**Pull request by yegor256**
closes #3747

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon please, check this one

File: eo-runtime/src/main/java/org/eolang/PhSafe.java [hunk 1]
```diff
@@ -197,25 +199,38 @@ private <T> T through(final Action<T> action, final String suffix) {
...
-                    .append(": ");
-            }
-            msg.append(ex.getClass().getSimpleName())
-                .append(": ")
-                .append(ex.getMessage());
             throw new EOerror.ExError(
-                new Data.ToPhi(msg.toString()),
-                this.label(suffix)
+                new Data.ToPhi(ex.getMessage()),
+                trace(ex, this.label(suffix))
```
Comment (maxonfjvipon) [inline eo-runtime/src/main/java/org/eolang/PhSafe.java:204]: @yegor256 let's make it `PhSafe.trace()`

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

File: eo-runtime/src/main/java/org/eolang/PhSafe.java (hunk 1 above)
Comment (yegor256) [reply eo-runtime/src/main/java/org/eolang/PhSafe.java]: @maxonfjvipon fixed in 698c11f9d
