### PR TITLE
bug(#4263): extract Java placing logic from `MjTranspile`

### LINKED ISSUE #4263: Refactoring Required in MjTranspile.apply() function for Code Consistency
The puzzle `4235-46fa6896` from #4235 has to be resolved: 

https://github.com/objectionary/eo/blob/0cd600370e18ecf9c63610bd4e9e3abed7a5eca5/eo-maven-plugin/src/main/java/org/eolang/maven/MjTranspile.java#L309-L312

The puzzle was created by @yegor256 on 08-Jun-25. 

Estimate: 35 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've extracted logic of placing Java source and test code from `MjTranspile` into several classes, in order to simplify `MjTranspile`, and make it's parts more testable.

closes #4263

## Summary by CodeRabbit

- **New Features**
  - Introduced advanced caching and rewrite policies for generated Java files, improving build efficiency and file management.
  - Added new mechanisms for placing generated Java source and test files, including handling naming conflicts for test classes.
  - Enhanced reporting for file generation activities with detailed logging.

- **Bug Fixes**
  - Improved handling of Java test file placement to prevent naming conflicts with existing test files.

- **Tests**
  - Added comprehensive tests for caching behavior, Java file placement, and test generation to ensure correct functionality.

- **Refactor**
  - Simplified and modularized the logic for Java file generation and placement, resulting in clearer and more maintainable code.

### CODE REVIEW

File: eo-maven-plugin/src/main/java/org/eolang/maven/GeneratedEntry.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+import com.jcabi.log.Logger;
+import java.nio.file.Path;
+import java.util.concurrent.atomic.AtomicInteger;
+
+/**
+ * Generated entry.
+ * @since 0.56.7
+ */
+final class GeneratedEntry {
```
Comment (maxonfjvipon) [inline eo-maven-plugin/src/main/java/org/eolang/maven/GeneratedEntry.java]: @h1alexbel it's not clear what is this class and what it does, neither by its name, nor the documentation

**Comment by h1alexbel** [comment]
@maxonfjvipon reminder

**Review by maxonfjvipon — APPROVED** [review]

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Great job on the review! You've scored 9 points for this one: 12 base points, plus 6 for reviewing a whopping 699 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (that's a lot!), but we had to deduct 10 because there were only 4 comments. Remember, more comments can boost your score next time! Your total is now [+61](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the awesome work! 🚀

**Comment by 0crat** [comment]
@h1alexbel Thank you for your contribution! Your effort is appreciated, but we noticed that the code size was quite large. You've earned +8 points: +16 as a base reward, with a -8 deduction due to the high number of hits-of-code (699 ≥ 200). While we value your work, remember to [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) contributions concise for better maintainability. Your current balance stands at [+355](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work, and consider breaking larger changes into smaller, more manageable pieces in the future.
