### PR TITLE
Fixed bug related to caching.

### LINKED ISSUE #2492: Bug in caching
According to #2441 cargo compiler must not be сalled in the subsequent eo compilation. But it is.
We need to fix this bug so  compilation time will be decreased approximately by 12 seconds.

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2492 
Fixed the bug and added test.
I also edited Log message which was
 `Binarized native0.rs from org.eolang.rust-tests` but I suggest
 `Binarized native0.rs from org.eolang.rust-tests:Φ.org.eolang.rust-returns-positive-int.r.α0` which is more clear as for me.

---

### Focus of the PR:
This PR focuses on improving

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur could you please review these changes?

File: eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java [hunk 1]
```diff
@@ -54,9 +55,31 @@
     threadSafe = true,
     requiresDependencyResolution = ResolutionScope.COMPILE
 )
-@SuppressWarnings("PMD.LongVariable")
+@SuppressWarnings({"PMD.LongVariable", "PMD.StaticAccessToStaticFields"})
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java:58]: @levBagryansky Maybe we add todo here? And think about how to avoid this PMD exclusion later. But it is up to you

**Review by Graur — APPROVED** [review]
@levBagryansky I can't find out how to avoid static section, so I decided to accept this pull request

File: eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java (hunk 1 above)
Comment (levBagryansky) [reply eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java:58]: @Graur I think we should not avoid this exclusion because `StaticAccessToStaticFields` rule is for other cases.

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

File: eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java [hunk 2]
```diff
@@ -54,9 +55,31 @@
...
 public final class BinarizeMojo extends SafeMojo {
 
+    /**
+     * Name of executable file which is result of cargo building.
+     */
+    public static final String LIB;
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java:64]: @levBagryansky this is not a good design. Instead, do this:

```
private static final String LIB = BinarizeMojo.common();
private static String common() {
  //...
}
```

**Comment by levBagryansky** [comment]
@yegor256 please take a look

File: eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java (hunk 1 above)
Comment (yegor256) [reply eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java:58]: @levBagryansky maybe you can remove this suppression too

**Comment by yegor256** [comment]
@rultor merge
