### PR TITLE
#934  Transitive dependencies

### LINKED ISSUE #934: ResolveMojo+Central must fail if there are transitive dependencies
If the dependency we found contains any transitive dependencies, we should fail the build.

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Closes #934 
If the dependency we found contains any transitive dependencies we fail the build.

### CODE REVIEW

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+                .collect(Collectors.toList());
+        }
+
+        /**
+         * Apply all filters for Dependency.
+         *
+         * @param dependency Dependency
+         * @return True if all filters were passed
+         */
+        private boolean applyAllFilters(final Dependency dependency) {
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:101]: @volodya-lombrozo Can we rename this method? Like apply, match, test or something else. According to this: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+        JsonDependencies(final Path file) {
+            this.file = file;
+        }
+
+        @Override
+        public List<Dependency> toList() {
+            try {
+                final List<Dependency> all = new ArrayList<>(0);
+                if (Files.exists(this.file)) {
+                    Logger.info(this, String.format("Dependencies file: %s", this.file));
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:132]: @volodya-lombrozo Can we set this logger level to `debug`? To avoid output noise

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 3]
```diff
@@ -0,0 +1,178 @@
...
+                        final String version = obj.getString("version");
+                        final String scope = obj.getJsonArray("scopes").stream()
+                            .map(JsonValue::toString)
+                            .findFirst().orElseThrow(IllegalStateException::new);
+                        all.add(dependency(group, id, version, scope));
+                    }
+                }
+                return all;
+            } catch (final IOException ex) {
+                throw new IllegalStateException(ex);
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:149]: @volodya-lombrozo Can we specify this error message according to this: https://www.yegor256.com/2015/12/01/rethrow-exceptions.html

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 4]
```diff
@@ -0,0 +1,178 @@
...
+         *
+         * @param group Dependency group id
+         * @param artifact Dependency artifact id
+         * @param version Dependency version
+         * @param scope Dependency scope
+         * @return Maven dependency
+         * @checkstyle ParameterNumberCheck (10 lines)
+         */
+        @SuppressWarnings("PMD.UseObjectForClearerAPI")
+        private static Dependency dependency(
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:164]: @volodya-lombrozo Can we use ctor here? According to this: https://www.yegor256.com/2017/11/14/static-factory-methods.html

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+ */
+interface DependenciesPlugin {
+
+    /**
+     * Uploads and saves file with list of dependencies.
+     *
+     * @param origin Dependency which transitive dependencies we are interested of
+     * @return File with dependencies
+     */
+    Path dependenciesFile(Dependency origin);
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java:43]: @volodya-lombrozo Same here. Can we make this name simpler?

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java [hunk 6]
```diff
@@ -202,8 +220,36 @@ private Collection<Dependency> deps() throws IOException {
...
+        }
+    }
+
+    /**
+     * Check if dependency has transitive dependencies.
+     *
+     * @param dep Dependency
+     * @return True if has transitice dependencies
+     */
+    private boolean hasTransitiveDependencies(final Dependency dep) {
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java:245]: @volodya-lombrozo Same here. Can we make this name simpler?

**Review by Graur — CHANGES_REQUESTED** [review]

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 7]
```diff
@@ -0,0 +1,178 @@
...
+     * @return List of Maven Dependencies
+     */
+    List<Dependency> toList();
+
+    /**
+     * Filtered dependencies.
+     *
+     * @since 0.28.11
+     */
+    class FilteredDependencies implements Dependencies {
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:61]: @volodya-lombrozo Following adopted convention maybe worth to name it `DcsFiltered`

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 1 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @Graur Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 2 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @Graur Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 3 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @Graur Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java (hunk 5 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java]: @Graur Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java (hunk 6 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java]: @Graur Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 4 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @Graur Fixed. Please, take a look. `Dependency` doesn't have a constructor. I've inlined the method.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 7 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @mximp Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 8]
```diff
@@ -0,0 +1,178 @@
...
+            return this.filters.stream().allMatch(f -> f.test(dependency));
+        }
+    }
+
+    /**
+     * Dependencies uploaded from json file.
+     *
+     * @since 0.28.11
+     */
+    class JsonDependencies implements Dependencies {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @mximp Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java [hunk 9]
```diff
@@ -0,0 +1,57 @@
...
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Plugin saves all transitive dependencies to a file.
+ *
+ * @since 0.28.11
+ */
+interface DependenciesPlugin {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java]: @mximp Fixed. Please, take a look. Renamed to `DcsFIle`. wdyt?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphMavenPlugin.java [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+import org.apache.maven.project.MavenProject;
+import org.twdata.maven.mojoexecutor.MojoExecutor;
+
+/**
+ * Plugin for uploading transitive dependencies.
+ * You can read more <a href="https://github.com/ferstl/depgraph-maven-plugin">here</a>
+ *
+ * @since 0.28.11
+ */
+final class DepgraphMavenPlugin implements DependenciesPlugin {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphMavenPlugin.java]: @mximp Fixed. Please, take a look. Renamed to `DepgraphDcsFile`. wdyt?

File: eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+import java.util.List;
+import java.util.function.Predicate;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Encapsulates all transitive dependencies of an artifact.
+ *
+ * @since 0.28.11
+ */
+final class TransitiveDependencies implements Dependencies {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java]: @mximp Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+    public List<Dependency> toList() {
+        return this.dependencies.toList();
+    }
+
+    /**
+     * Filters runtime dependency eo-runtime.
+     *
+     * @since 0.28.11
+     */
+    private static final class NoRuntimeDependency implements Predicate<Dependency> {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java]: @mximp Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java [hunk 13]
```diff
@@ -0,0 +1,132 @@
...
+                );
+        }
+    }
+
+    /**
+     * Filters all dependencies with the same group and artifact id.
+     *
+     * @since 0.28.11
+     */
+    private static final class NoSameDependency implements Predicate<Dependency> {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java]: @mximp Fixed. Please, take a look.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (mximp) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesPlugin.java]: @volodya-lombrozo This is a base interface - it should be named as an entity.
Suffix notation `Dcs***` is used for concrete implementations.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java [hunk 14]
```diff
@@ -0,0 +1,129 @@
...
+import java.nio.file.Path;
+import org.apache.maven.execution.MavenSession;
+import org.apache.maven.model.Dependency;
+import org.apache.maven.plugin.BuildPluginManager;
+import org.apache.maven.plugin.MojoExecutionException;
+import org.apache.maven.project.MavenProject;
+import org.twdata.maven.mojoexecutor.MojoExecutor;
+
+/**
+ * Plugin for uploading transitive dependencies.
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java:35]: @volodya-lombrozo Is this a plugin?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java [hunk 15]
```diff
@@ -0,0 +1,129 @@
...
+ * You can read more <a href="https://github.com/ferstl/depgraph-maven-plugin">here</a>
+ *
+ * @since 0.28.11
+ */
+final class DepgraphDcsFile implements DcsFile {
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java]: @volodya-lombrozo should be `DfGraph`?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java [hunk 16]
```diff
@@ -0,0 +1,57 @@
...
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Plugin saves all transitive dependencies to a file.
+ *
+ * @since 0.28.11
+ */
+interface DcsFile {
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java]: @volodya-lombrozo Is this entity actually related to file? What property of its contract tell us something about the file? As I see from its methods it something with dependencies.
Generally it's not clear what this entity represents.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java [hunk 17]
```diff
@@ -0,0 +1,57 @@
...
+
+    /**
+     * Uploads and saves file with list of dependencies.
+     *
+     * @param origin Dependency which transitive dependencies we are interested of
+     * @return File with dependencies
+     */
+    Path dependencies(Dependency origin);
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java]: @volodya-lombrozo How do we reference a file here? Based on description of a method we should supply file at some point but the contract provides no means for that.
Also please check [this post](https://www.yegor256.com/2018/08/22/builders-and-manipulators.html) for methods design

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java [hunk 18]
```diff
@@ -0,0 +1,135 @@
...
+import java.util.Arrays;
+import java.util.function.Predicate;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Encapsulates all transitive dependencies of an artifact.
+ *
+ * @since 0.28.11
+ */
+final class DcsTransitive {
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java:36]: @volodya-lombrozo Is it supposed to implement any interface? It has `Dcs` prefix - supposed to be `Dependencies` implementation?

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 19]
```diff
@@ -0,0 +1,165 @@
...
+ * @since 0.28.11
+ */
+interface Dependencies {
+
+    /**
+     * Converts to a plain list.
+     *
+     * @return List of Maven Dependencies
+     */
+    List<Dependency> toList();
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:54]: @volodya-lombrozo can be just `list()`

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 20]
```diff
@@ -0,0 +1,165 @@
...
+import javax.json.JsonReader;
+import javax.json.JsonValue;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Maven dependencies abstraction.
+ *
+ * @since 0.28.11
+ */
+interface Dependencies {
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:47]: @volodya-lombrozo Maybe it can implement `Iterable`? As far as I understand it is just a collection of items.

**Comment by mximp** [comment]
@volodya-lombrozo Please check some comments on the design and naming above.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 20 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:47]: Yes, but I will use `Collections if you don't mind. I need the `stream()` method

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java (hunk 18 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java:36]: It was, but we don't need `all` method in that class and we don't use `DscTransitive` ad decorator. I think its better to extend the name

Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java:36]: Renamed to `TransitiveDependencies`

File: eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java (hunk 15 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java]: `Depgraph` it is the name of the maven plugin that we are using for retrieving dependencies file. I think it's better to leave that name in order to emphasise the source.

Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java]: Please, take a look https://github.com/ferstl/depgraph-maven-plugin

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 20 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:47]: @mximp Fixed.

Comment (mximp) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:47]: @volodya-lombrozo with `Collection` you will have to implement all of its methods... and do it in every class. Do you really need such a heavy contract in this case?

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 19 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java]: @mximp Fixed. `all` since we are using `Collection` for now

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java (hunk 18 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java]: @mximp Fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java (hunk 17 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java]: @mximp Fixed. Renamed to `file()`

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java (hunk 16 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java]: @mximp Fixed. The class and his method was renamed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java (hunk 15 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java]: @mximp

File: eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java (hunk 14 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DepgraphDcsFile.java]: @mximp Fixed. The description is changed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java (hunk 17 above)
Comment (mximp) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java]: @volodya-lombrozo Can you please reply to the comment above: what this class represents?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java (hunk 16 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsFile.java]: @mximp 
```java
interface DependenciesFile {
    Path file(Dependency origin);
}
```

The idea is return the file which contains all transient dependencies of the `origin` dependency.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 20 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:47]: @mximp I got your idea. No, I don't think we have to implement `Iterable` class - it's an overdesign. We just don't need it. Moreover, I need only `path`.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java [hunk 21]
```diff
@@ -0,0 +1,57 @@
...
+ */
+interface DependenciesFile {
+
+    /**
+     * Returns the link to the file with the list of dependencies.
+     *
+     * @param origin Dependency which transitive dependencies we are interested of
+     * @return File with dependencies
+     */
+    Path file(Dependency origin);
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java:43]: @volodya-lombrozo It is still awkward design here. We have a **File** object which has _file_ attribute. I would expect a **File** to have _path_. 
Also this method accepts particular dependency - does that mean that returned path would contain a file with dependencies for this dependency only?
And `DependenciesFile` represents a file with all possible transitive dependencies?
How would I see it:
```
Path path = new DependenciesFileImpl(origin).path();
```

File: eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java [hunk 22]
```diff
@@ -0,0 +1,135 @@
...
+import java.util.Arrays;
+import java.util.function.Predicate;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Encapsulates all transitive dependencies of an artifact.
+ *
+ * @since 0.28.11
+ */
+final class TransitiveDependencies {
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/TransitiveDependencies.java]: @mximp Fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java (hunk 21 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java]: @mximp I've implemented the new structure of classes. Please check. Some points:
1) We don't have `TransitiveDependencies` anymore.
2) Also `DependenciesFile` and connected implementations were removed.
3) Predicates still exists, because if we will define them right into `ResolveMojo` (as lambdas) - we won't be able to test them. Also it's impossible to define them: 
3.1)  as `static field`  - we have to provide particular dependency for `NotSame` predicate. 
3.2) as `factory method` - pure design
3.3) Of course, we can introduce one more specific class, like `DcsTransitive`:
```java
public class DcsTransitive implements Dependencies {

    private final Dependencies delegate;

    public DcsTransitive(final Dependencies delegate, final Dependency origin) {
        this.delegate = new DcsFiltered(
            delegate,
            Arrays.asList(
                new DcsFiltered.NotSame(origin),
                new DcsFiltered.NotRuntime(),
                new DcsFiltered.NotTesting()
            )
        );
    }

    @Override
    public Collection<Dependency> all() {
        return delegate.all();
    }
}
```
but, as I understand, you against it, because it's an overdesign.

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java [hunk 23]
```diff
@@ -202,8 +215,43 @@ private Collection<Dependency> deps() throws IOException {
...
+                            new DcsFiltered.NotRuntime(),
+                            new DcsFiltered.NotSame(dep),
+                            new DcsFiltered.NotTesting()
+                        )
+                    ).all().isEmpty()) {
+                        throw new IllegalStateException(
+                            String.format("%s contains transitive dependencies", dep)
+                        );
+                    }
+                });
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java:248]: @volodya-lombrozo parenthesis should be on new line here

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java (hunk 21 above)
Comment (mximp) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java]: @volodya-lombrozo Actually, it's a very good idea... `DcsTransitive` in this form looks fine in this form. Can you add it and use?

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java (hunk 23 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java]: @mximp fixed

File: eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java (hunk 21 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DependenciesFile.java]: @mximp Added.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java [hunk 24]
```diff
@@ -0,0 +1,63 @@
...
+ * SOFTWARE.
+ */
+package org.eolang.maven;
+
+import java.util.Arrays;
+import java.util.Collection;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Test case for {@link org.eolang.maven.DcsTransitive}.
```
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java]: :) @mximp fixed

**Review by mximp — APPROVED** [review]

**Comment by mximp** [comment]
@Graur do you approve?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java [hunk 25]
```diff
@@ -0,0 +1,218 @@
...
+                ),
+                MojoExecutor.executionEnvironment(
+                    this.project,
+                    this.session,
+                    this.manager
+                )
+            );
+            return this.dir.resolve(name);
+        } catch (final MojoExecutionException ex) {
+            throw new IllegalStateException(ex);
```
Comment (Graur) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java:139]: @volodya-lombrozo Can we specify this error message according to this: https://www.yegor256.com/2015/12/01/rethrow-exceptions.html

**Review by Graur — CHANGES_REQUESTED** [review]
@volodya-lombrozo Good one, just a small comment from my side:

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java (hunk 25 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java]: @Graur Done

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good to me, thanks!

**Comment by volodya-lombrozo** [comment]
@yegor256 can you merge please?

**Review by mximp — APPROVED** [review]

File: eo-maven-plugin/pom.xml [hunk 26]
```diff
@@ -169,13 +169,11 @@ SOFTWARE.
       <groupId>javax.json</groupId>
       <artifactId>javax.json-api</artifactId>
       <version>1.1.4</version>
-      <scope>runtime</scope>
```
Comment (yegor256) [inline eo-maven-plugin/pom.xml:172]: @volodya-lombrozo maybe it's better to replace with `provided`? https://howtodoinjava.com/maven/maven-dependency-scopes/

File: eo-maven-plugin/pom.xml [hunk 27]
```diff
@@ -169,13 +169,11 @@ SOFTWARE.
...
     </dependency>
     <dependency>
       <groupId>org.glassfish</groupId>
       <artifactId>javax.json</artifactId>
       <version>1.1.4</version>
-      <scope>runtime</scope>
```
Comment (yegor256) [inline eo-maven-plugin/pom.xml:178]: @volodya-lombrozo are you sure? Usually `-api` stays in `compile`, while implementation stays in `runtime`.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java (hunk 20 above)
Comment (yegor256) [reply eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:34]: @volodya-lombrozo I agree that `Iterable` would be a better interface for `DcsDepgraph`. When you need `.size()`, just use `LengthOf(Iterable)` from Cactoos.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java [hunk 28]
```diff
@@ -0,0 +1,224 @@
...
+                    this.project,
+                    this.session,
+                    this.manager
+                )
+            );
+            return this.dir.resolve(name);
+        } catch (final MojoExecutionException ex) {
+            throw new IllegalStateException(
+                String.format(
+                    "Dphgraph. Uploading of dependencies file failed for the dependency %s",
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java:141]: @volodya-lombrozo uploading, really? I don't think we upload anything here

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java [hunk 29]
```diff
@@ -0,0 +1,224 @@
...
+                        dependency.setVersion(version);
+                        dependency.setScope(scope);
+                        all.add(dependency);
+                    }
+                }
+                return all;
+            } catch (final IOException | IllegalStateException ex) {
+                throw new IllegalStateException(
+                    String.format(
+                        "Exception happens during reading the dependencies from json file %s. %s",
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java:215]: @volodya-lombrozo it's better to use a long line here. Qulice won't complain

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFiltered.java [hunk 30]
```diff
@@ -0,0 +1,137 @@
...
+import java.util.function.Predicate;
+import java.util.stream.Collectors;
+import org.apache.maven.model.Dependency;
+
+/**
+ * Filtered dependencies.
+ *
+ * @since 0.28.11
+ */
+class DcsFiltered implements Dependencies {
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsFiltered.java:36]: @volodya-lombrozo if you would use `Iterable`, you wouldn't need this class, but would be able to use `Filtered` from Cactoos: https://www.javadoc.io/doc/org.cactoos/cactoos/latest/org/cactoos/iterable/package-summary.html

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java [hunk 31]
```diff
@@ -95,6 +98,14 @@ public final class ResolveMojo extends SafeMojo {
     @SuppressWarnings("PMD.ImmutableField")
     private BiConsumer<Dependency, Path> central;
 
+    /**
+     * Check transitive dependencies.
+     *
+     * @checkstyle MemberNameCheck (7 lines)
+     */
+    @SuppressWarnings({"PMD.ImmutableField", "PMD.AvoidFieldNameMatchingMethodName"})
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java:106]: @volodya-lombrozo this is a valid concern of PMD: AvoidFieldNameMatchingMethodName. Don't use similar names for methods and attrs

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java [hunk 32]
```diff
@@ -202,8 +214,40 @@ private Collection<Dependency> deps() throws IOException {
...
 
+    /**
+     * Check if all dependencies have transitive dependencies.
+     *
+     * @param deps Dependencies
+     * @throws java.lang.IllegalStateException if a transitive dependency is found
+     */
+    private void checkTransitive(final Collection<Dependency> deps) {
+        if (this.checkTransitive) {
+            deps.forEach(
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java:225]: @volodya-lombrozo compare this:

```
list.forEach(
  a -> {
    doit();
  }
)
```

with this:

```
for (list : a) {
  doit();
)
```

which is more compact and has less indentation?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java (hunk 29 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java]: @yegor256 fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java (hunk 31 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java]: @yegor256 fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java (hunk 32 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java]: @yegor256 fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsFiltered.java (hunk 30 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsFiltered.java]: @yegor256 I've used `Filetered` inside `DcsTransitive` and removed `DcsFiltered`

**Comment by volodya-lombrozo** [comment]
@yegor256 I've changed the code according with your suggestions. Take a look, please.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java [hunk 33]
```diff
@@ -0,0 +1,223 @@
...
+                        dependency.setVersion(version);
+                        dependency.setScope(scope);
+                        all.add(dependency);
+                    }
+                }
+                return all;
+            } catch (final IOException | IllegalStateException ex) {
+                throw new IllegalStateException(
+                    String.format(
+                        "Exception happens during reading the dependencies from json file %s. Probably the file is absent or you have a wrong json format",
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsDepgraph.java:215]: @volodya-lombrozo for the future, try to enclose `%s` inside texts with single quotes. This will help readers separate your enclosures from the rest of the text:

```
... reading from JSON file '%s`, probably the file...
```

Also, try to use ONE sentence as error message, without a dot inside (and no dot at the end)

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java [hunk 34]
```diff
@@ -0,0 +1,138 @@
...
+     * @param origin The dependency that transitive dependencies we are interested of
+     */
+    DcsTransitive(final Dependencies delegate, final Dependency origin) {
+        this.delegate = delegate;
+        this.origin = origin;
+    }
+
+    @Override
+    public Collection<Dependency> all() {
+        return StreamSupport.stream(
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java:64]: @volodya-lombrozo why do you need streams at all? My suggestion, don't use Java streams at all -- their design is pretty anti-OOP in Java. Better use Cactoos primitives. They do the same, but the code will look much more readable and maintainable.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java [hunk 35]
```diff
@@ -0,0 +1,138 @@
...
+            ((Iterable<Dependency>) () -> new Filtered<>(
+                new Filtered<>(
+                    new Filtered<>(
+                        this.delegate.all().iterator(),
+                        new NotSame(this.origin)
```
Comment (yegor256) [inline eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java:69]: @volodya-lombrozo if you get rid of streams, you will see that here you don't need such special small classes. You can easily inline them right into this big decorator.

**Comment by yegor256** [comment]
@volodya-lombrozo I still don't understand why can't you use `Iterable`? What's the point of making this new interface `Dependencies`?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java (hunk 35 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java]: @yegor256 fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java (hunk 34 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java]: @yegor256 fixed.

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo I still don't understand why can't you use `Iterable`? What's the point of making this new interface `Dependencies`?

@yegor256 I used `Iterable`, removed streams and fixed exception message.  Also I've tried to simplify `DcsTransitive` by removing small predicate classes. wdyt?

File: eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java (hunk 35 above)
Comment (volodya-lombrozo) [reply eo-maven-plugin/src/main/java/org/eolang/maven/DcsTransitive.java]: @yegor256 fixed.

File: eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java [hunk 36]
```diff
@@ -0,0 +1,34 @@
...
+package org.eolang.maven;
+
+import org.apache.maven.model.Dependency;
+
+/**
+ * Maven dependencies abstraction.
+ *
+ * @since 0.28.11
+ */
+interface Dependencies extends Iterable<Dependency> {
```
Comment (mximp) [inline eo-maven-plugin/src/main/java/org/eolang/maven/Dependencies.java:33]: @volodya-lombrozo @yegor256 now a question: do we really need this "marker" interface or maybe we can replace all references to `Iterable<Dependency>`?

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@rultor merge
